name: Test Github Action
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile new test
        uses: ./
        with:
          root_file: test/test.tex test/eps.tex
          working_directory: ./
          pre_compile: |
              echo "new test begin"
              pwd
              ls
          post_compile: |
              echo "new test end"
              pwd
              ls
      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: test
          path: test
        if: always()
